[project]
name = "setup-uv-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nextflow==23.10.1",
    "pytest==7.2.0",
    "pytest-workflow==2.0.1",
]
