name: setup java and uv

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'

      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          cache-dependency-glob: "**/uv.lock"
          python-version: 3.13t
      - run: uv pip install --python=3.13t pip pytest=7.2.0 pytest-worflow=2.0.1 nextflow=23.10.1

