name: setup java and uv

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'

      - name: setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          activate-environment: true
          python-version: 3.11
      - run: uv pip install -r pyproject.toml

      - name: run test
        run: bash script.sh

